//@version=4

strategy(title="Martingale",calc_on_order_fills=true,calc_on_every_tick =false, initial_capital=12000,commission_type=strategy.commission.percent, commission_value=0.2,overlay = true,default_qty_type = strategy.cash, default_qty_value = 12000)
buffer = input(title="buffer", type=input.float, defval=0.3, minval = 0, step = 0.1)
b1 = close[1]* (1+buffer/100)
b2 = close[1]* (1-buffer/100)
strategy.entry("Long", true, when =  close > b1, comment = "entry")
strategy.close("Long", when=close <b2, comment = "exit")
//money management
stop_loss=input(15, "Stop loss %", minval = 1, step = 1)
sl = strategy.position_avg_price * (1-stop_loss/100)
close_Stop = close < sl
strategy.close("Long", when = close_Stop, comment = "Stop loss")
Target_profit=input(50, "Target Profit %", minval = 1, step = 1)
tp = strategy.position_avg_price * (1+Target_profit/100)
close_Target = close > tp
strategy.close("Long", when = close_Target, comment ="Target")
