//@version=5
// 沒有賺錢
strategy("RSI-止損-策略-20231215", overlay=true)
length = input( 14 )
overSold = input( 30 )
overBought = input( 70 )
price = close
vrsi = ta.rsi(price, length)
co = ta.crossover(vrsi, overSold)
cu = ta.crossunder(vrsi, overBought)
if (not na(vrsi))
    if (co)
        strategy.entry("RsiLE", strategy.long, comment="RsiLE")
    if (cu)
        strategy.entry("RsiSE", strategy.short, comment="RsiSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)

// stop
opentrades = strategy.opentrades
entryPrice = strategy.opentrades.entry_price(opentrades - 1)
if (strategy.position_size > 0)
    strategy.exit("RsiLE exit", "RsiLE", qty_percent = 100, stop = entryPrice * 0.98)

if (strategy.position_size < 0)
    strategy.exit("RsiSE exit", "RsiSE", qty_percent = 100, stop = entryPrice * 1.02)
